### ISSUE TITLE
Исключение при сборе rbc

### ISSUE THREAD

**Issue by stroykova** [newsviz/Spiders#13]
Данные не собираются
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/code/newsbot/pipelines.py", line 38, in process_item
    item["title"] = spider.process_title(item["title"][0])
  File "/usr/local/lib/python3.7/site-packages/scrapy/item.py", line 93, in __getitem__
    return self._values[key]
KeyError: 'title'

```

**Comment by Avenon** [comment]
Поправил в PR: https://github.com/newsviz/Spiders/pull/20
