### ISSUE TITLE
Исключение при сборе ria

### ISSUE THREAD

**Issue by stroykova** [newsviz/Spiders#14]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/code/newsbot/pipelines.py", line 36, in process_item
    dt = datetime.datetime.strptime(item["date"][0], spider.config.date_format)
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2021-03-21T11:19' does not match format '%Y-%m-%dT%H:%MZ'

```

**Comment by Avenon** [comment]
Поправил: https://github.com/newsviz/Spiders/pull/20
