### ISSUE TITLE
Исключение в spider-е rbc

### ISSUE THREAD

**Issue by wofka72** [newsviz/Spiders#22]
Выбрасывается исключение в `rbc`. Это происходит из-за некорректного на данный момент xpath к title

```
Traceback (most recent call last):
  File "/home/vett0/miniconda3/envs/newsviz/lib/python3.8/site-packages/twisted/internet/defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/vett0/miniconda3/envs/newsviz/lib/python3.8/site-packages/scrapy/utils/defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "/home/vett0/projects/newsviz/Spiders2/newsbot/pipelines.py", line 34, in process_item
    item["title"] = spider.process_title(item["title"][0])
  File "/home/vett0/miniconda3/envs/newsviz/lib/python3.8/site-packages/scrapy/item.py", line 94, in __getitem__
    return self._values[key]
KeyError: 'title'
```

**Comment by wofka72** [comment]
Дубликат #13
